update yml

diff --git a/.github/workflows/minesweeper.yml b/.github/workflows/minesweeper.yml
--- a/.github/workflows/minesweeper.yml
+++ b/.github/workflows/minesweeper.yml
@@ -11,51 +11,43 @@ jobs:
     strategy:
       matrix:
         os: [ubuntu-latest, macos-latest, windows-latest]
-    
+
     steps:
       - uses: actions/checkout@v2
       - name: install cppunit
         run: |
-          if ( "${{ matrix.os }}" == "ubuntu-latest" ) {
+          if ( "${{ matrix.os }}" == "ubuntu-latest" ) then
             sudo apt install -y libcppunit-dev
-          }
-          elif ( "${{ matrix.os }}" == "macos-latest" ) {
+          elif ( "${{ matrix.os }}" == "macos-latest" ) then
             brew install cppunit
-          }
-          
+          fi
       - name: make
         run: |
-          if ( "${{ matrix.os }}" == "ubuntu-latest" ) {
+          if ( "${{ matrix.os }}" == "ubuntu-latest" ) then
             make
-          }
-          elif ( "${{ matrix.os }}" == "macos-latest" ) {
+          elif ( "${{ matrix.os }}" == "macos-latest" ) then
             clang++ -I. -std=c++17 -o test minesweeper.cpp test.cpp -lcppunit
-          }
-          
+          fi
       - name: make test
         run: |
-          if ( "${{ matrix.os }}" == "ubuntu-latest" ) {
+          if ( "${{ matrix.os }}" == "ubuntu-latest" ) then
             make test
             exit_code=$?
 
-            if [ $exit_code -eq 0 ]; {
+            if [ $exit_code -eq 0 ]; then
               echo "All tests passed. Allowing push..."
               exit 0
-            }
             else
-            {
-              echo "Tests failed. Blocking push..."
-              exit
-            }
-          }
-          elif ( "${{ matrix.os }}" == "macos-latest" ) {
-            ./test
-            if [ $? -eq 0 ]{
-              echo "All tests passed. Allowing push..."
-              exit 0
-            }
-            else{
               echo "Tests failed. Blocking push..."
               exit 1
-            }
-          }
+            fi
+          elif ( "${{ matrix.os }}" == "macos-latest" ) then
+            ./test
+            if [ $? -eq 0 ]; then
+              echo "All tests passed. Allowing push..."
+              exit 0
+            else
+              echo "Tests failed. Blocking push..."
+              exit 1
+            fi
+          fi
