update yml

diff --git a/.github/workflows/minesweeper.yml b/.github/workflows/minesweeper.yml
--- a/.github/workflows/minesweeper.yml
+++ b/.github/workflows/minesweeper.yml
@@ -18,11 +18,15 @@ jobs:
         run: |
           if ( "${{ matrix.os }}" == "ubuntu-latest" ) then
             sudo apt install -y libcppunit-dev
+          elif ( "${{ matrix.os }}" == "macos-latest" ) then
+            brew install cppunit
           fi
       - name: make
         run: |
           if ( "${{ matrix.os }}" == "ubuntu-latest" ) then
             make
+          elif ( "${{ matrix.os }}" == "macos-latest" ) then
+            clang++ -I. -std=c++17 -o test minesweeper.cpp test.cpp -lcppunit
           fi
       - name: make test
         run: |
@@ -31,6 +35,15 @@ jobs:
             exit_code=$?
 
             if [ $exit_code -eq 0 ]; then
+              echo "All tests passed. Allowing push..."
+              exit 0
+            else
+              echo "Tests failed. Blocking push..."
+              exit 1
+            fi
+          elif ( "${{ matrix.os }}" == "macos-latest" ) then
+            ./test
+            if [ $? -eq 0 ]; then
               echo "All tests passed. Allowing push..."
               exit 0
             else
