update yml

diff --git a/.github/workflows/minesweeper.yml b/.github/workflows/minesweeper.yml
--- a/.github/workflows/minesweeper.yml
+++ b/.github/workflows/minesweeper.yml
@@ -28,13 +28,15 @@ jobs:
             fi
         - name: make test
           run: |
-            make test
-            exit_code=$?
+            if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
+              make test
+              exit_code=$?
 
-            if [ $exit_code -eq 0 ]; then
-              echo "All tests passed. Allowing push..."
-              exit 0
-            else
-              echo "Tests failed. Blocking push..."
-              exit 1
+              if [ $exit_code -eq 0 ]; then
+                echo "All tests passed. Allowing push..."
+                exit 0
+              else
+                echo "Tests failed. Blocking push..."
+                exit 1
+              fi
             fi
